name: Create envfile

on:
  workflow_dispatch:

jobs:

  create-envfile:
 
    runs-on: ubuntu-latest
 
    steps:
    - name: Make envfile
      uses: SpicyPizza/create-envfile@v2.0
      with:
        API_CLIENT_EMAIL: ${{ secrets.API_CLIENT_EMAIL }}
        API_PRIVATE_KEY: ${{ secrets.API_PRIVATE_KEY }}
        SHEET_ID: ${{ secrets.SHEET_ID }}
